#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine with Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
